[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs_18", "python311", "python311Packages.pip"]

[phases.install]
  cmds = ["npm ci --omit=dev"]

[phases.build] 
  cmds = ["npm run build"]

[start]
  cmd = "./start.sh"
