[variables]
  NODE_ENV = "production"

[providers]
  python = "3.11"
  node = "18"

[phases.install]
  cmds = ["npm ci --omit=dev"]

[phases.build] 
  cmds = ["npm run build"]

[start]
  cmd = "./start.sh"
