[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs_18", "python311", "python311Packages.pip"]

[phases.install]
  cmds = [
    "npm ci --omit=dev",
    "cd backend && python -m pip install --upgrade pip",
    "cd backend && python -m pip install -r requirements.txt"
  ]

[phases.build]
  cmds = ["npm run build"]

[start]
  cmd = "cd backend && python main.py"
