/**
 * ICUI Framework - Main Entry Point
 * Exports all ICUI components, hooks, and types
 */

// Components
export { ICUIFrameContainer } from './components/ICUIFrameContainer';
export { ICUISplitPanel } from './components/ICUISplitPanel';
export { ICUILayoutPresetSelector } from './components/ICUILayoutPresetSelector';
export { ICUIBasePanel } from './components/ICUIBasePanel';
export { ICUIPanelHeader } from './components/ICUIPanelHeader';
export { ICUIPanelContent } from './components/ICUIPanelContent';
export { ICUIPanelArea } from './components/ICUIPanelArea';

// Specialized Panels (Phase 4)
export { default as ICUITerminalPanel } from './components/panels/ICUITerminalPanel';
export { ICUIEditorPanel } from './components/panels/ICUIEditorPanel';
export { ICUIExplorerPanel } from './components/panels/ICUIExplorerPanel';

// Hooks
export { useICUIResponsive } from './hooks/icui-use-responsive';
export { useICUILayoutState, useCurrentLayout, useLayoutPresets } from './hooks/icui-use-layout-state';
export { useICUIPanels, createPanel, PanelUtils } from './hooks/icui-use-panels';

// Types
export type {
  ICUISize,
  ICUIPosition,
  ICUIBorder,
  ICUIResizeHandle,
  ICUIFrameConfig,
  ICUILayoutGrid,
  ICUIViewport,
  ICUIBreakpoint,
  ICUIResponsiveConfig,
} from './types/icui-layout';

export type {
  ICUISplitDirection,
  ICUISplitMode,
  ICUISplitConfig,
  ICUISplitPanelState,
  ICUISplitHandle,
  ICUISplitPanelProps,
} from './types/icui-split';

export type {
  ICUILayoutPresetType,
  ICUILayoutState,
  ICUIPanelState,
  ICUILayoutPreset,
  ICUILayoutManagerState,
  ICUILayoutActions,
  ICUILayoutPersistence,
  ICUILayoutHookResult,
} from './types/icui-layout-state';

export type {
  ICUIPanelType,
  ICUIPanelState as ICUIPanelInstanceState,
  ICUIPanelContentType,
  ICUIPanelConfig,
  ICUIPanelContextMenuItem,
  ICUIPanelPosition,
  ICUIPanelInstance,
  ICUIPanelHeaderProps,
  ICUIPanelContentProps,
  ICUIBasePanelProps,
  ICUIPanelActions,
  ICUIPanelManagerState,
  ICUIPanelHookResult,
} from './types/icui-panel';

// Version
export const ICUI_VERSION = '4.0.0';

// Framework info
export const ICUI_INFO = {
  name: 'ICUI Framework',
  version: ICUI_VERSION,
  description: 'Interactive Component UI Framework - Modular panel system inspired by Blender',
  author: 'Generated by AI Assistant',
  license: 'MIT',
};
