name: MCP Test Workflow
on:
  push:
    branches: [ main, 20-icui-improvements ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test MCP Integration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Success message
      run: |
        echo "🎉 SUCCESS! This workflow was created to test MCP functionality"
        echo "✅ GitHub PAT is working correctly"
        echo "✅ Repository access is functional"
